[pytest]
addopts =
    --durations-min=30.0
    --durations=0
markers =
    slow: medium-complexity tests, like integration tests, on a single GPU
    multi_gpu: tests that require multiple GPUs
    distributed: tests that require distributed setup via torchrun execution
